### ISSUE TITLE
GPU Count 0, curve not showing on the Utilization tab

### ISSUE THREAD

**Issue by Tianyangg** [congard/nvidia-system-monitor-qt#16]
![image](https://user-images.githubusercontent.com/39927555/114174891-e061fa80-996b-11eb-86e9-f621571d4438.png)
Hi, this command gives me gpucount=8 while starting build/qnvsm gives 
![image](https://user-images.githubusercontent.com/39927555/114174980-012a5000-996c-11eb-87e1-3f0002508ab9.png)

the monitor is not showing anything on the Utilization tab (the process tab seems working)
![image](https://user-images.githubusercontent.com/39927555/114175181-48b0dc00-996c-11eb-9150-97b66b41333c.png)
![image](https://user-images.githubusercontent.com/39927555/114175029-17d0a700-996c-11eb-885c-1689b93c7998.png)
Any idea about this please could you let me know?
Thank you.

**Comment by congard** [comment]
Hi, thank you for your report. Could you test the latest master, please?

**Comment by Tianyangg** [comment]
> Hi, thank you for your report. Could you test the latest master, please?

I think its now working, Thx :D
![image](https://user-images.githubusercontent.com/39927555/114373704-7177e200-9bb5-11eb-90dc-dcd4f21822ee.png)
