### ISSUE TITLE
1.3 does not launch on ubuntu 20.04

### ISSUE THREAD

**Issue by Cervoxx** [congard/nvidia-system-monitor-qt#19]
Attempting to launch it gives this error: 

> qnvsm: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by qnvsm)

**Comment by congard** [comment]
Have you installed `deb` package?

**Comment by Cervoxx** [comment]
Yes, this error comes from the deb package.

**Comment by ParthMandaliya** [comment]
I am also facing the same issue on ubuntu 20.04

**Comment by ParthMandaliya** [comment]
@Cervoxx, you can follow this article to install this tool manually. But remember to make a small change after you clone this repo, as I have mentioned here in this issue https://github.com/congard/nvidia-system-monitor-qt/issues/20#issuecomment-1003135222

**Comment by congard** [comment]
Closed as "Possibly solved"

**Comment by congard** [comment]
Please, try [the latest release](https://github.com/congard/nvidia-system-monitor-qt/releases/tag/v1.5) and let me know if it works

**Comment by Cervoxx** [comment]
It boots!
