### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ParthMandaliya** [congard/nvidia-system-monitor-qt#20]
After problems with Debian package, I tried to build it from the source by following the article from here https://www.linuxuprising.com/2019/06/2-tools-for-monitoring-nvidia-gpus-on.html . I was able to build qnvsm but while running the command 
"Connecting to nvidia-smi...
Segmentation fault (core dumped)" 
error is coming

**Comment by ParthMandaliya** [comment]
I have debugged the issue for you.
Here are the steps for you to resolve this.
https://github.com/congard/nvidia-system-monitor-qt/blob/bdc5b3c59e4a6cece46d2f2938deefa342f96b68/src/core/NVSMIParser.cpp#L135

It should not be ```temperature.memory```, it should be ```utilization.memory```

**Comment by congard** [comment]
@ParthMandaliya could you post the output of `nvidia-smi --query-gpu=temperature.gpu,temperature.memory,power.draw --format=csv,noheader,nounits` command?

**Comment by ParthMandaliya** [comment]
@congard 
Field "temperature.memory" is not a valid field to query.

**Comment by ParthMandaliya** [comment]
Here is the nvidia official link for you https://nvidia.custhelp.com/app/answers/detail/a_id/3751/~/useful-nvidia-smi-queries

**Comment by congard** [comment]
Well, but field `temperature.memory` exists:
```bash
> nvidia-smi --help-query-gpu | grep temperature
"temperature.gpu"
 Core GPU temperature. in degrees C.
"temperature.memory"
 HBM memory temperature. in degrees C.
```

**Comment by congard** [comment]
What version of drivers are you using?

**Comment by ParthMandaliya** [comment]
```sh
 HW Thermal Slowdown: temperature being too high
HW Thermal Slowdown (reducing the core clocks by a factor of 2 or more) is engaged. This is an indicator of temperature being too high
"temperature.gpu"
 Core GPU temperature. in degrees C.
```
what version of nvidia driver, you mean? @congard

**Comment by congard** [comment]
@ParthMandaliya Yeah, of course

**Comment by ParthMandaliya** [comment]
390.144

**Comment by congard** [comment]
Understood. I'll fix it tomorrow

**Comment by congard** [comment]
Could you test the latest commit on master, please?

**Comment by ParthMandaliya** [comment]
Sure will do
