### ISSUE TITLE
How to build with github action ?

### ISSUE THREAD

**Issue by Jeevasimba** [congard/nvidia-system-monitor-qt#23]
I want to compile my code with Compile: qmake && make.

https://github.com/PradeepSimba/test/blob/main/.github/workflows/main.yml

But , If I run it comes an error .

https://github.com/PradeepSimba/test/runs/6637488143?check_suite_focus=true#step:7:59

How can I solve this error ?

**Comment by congard** [comment]
You have a clear error message: `Makefile.Release:70: *** missing separator.  Stop.`. So you should find an error in your code by yourself or ask a question for example on [stackoverflow.com](https://stackoverflow.com).
