### ISSUE TITLE
Missing C+G processes

### ISSUE THREAD

**Issue by pstrejajo** [congard/nvidia-system-monitor-qt#24]
There are missing C+G processes in the list. Regexp in https://github.com/congard/nvidia-system-monitor-qt/blob/93019827b7b711cf6f8ac79eebd8a8806460c5e7/src/core/InfoProvider.cpp#L72 matches only C or G, but not C+G.

I have changed the regexp in 14822ca and it looks ok now:
![image](https://user-images.githubusercontent.com/31010659/172733792-39c9ab28-5e72-4dd0-842b-4268fa06f345.png)

**Comment by congard** [comment]
Thank you for your contribution. Merged to master
