### ISSUE TITLE
Feature request: Make the window scrollable

### ISSUE THREAD

**Issue by jankais3r** [congard/nvidia-system-monitor-qt#27]
Hi,

I installed the flatpak release on Ubuntu Mate 22.04 and I don't see any charts in the GUI.

![image](https://user-images.githubusercontent.com/2159464/217876449-59605044-1f6a-47e7-9b26-e4e651c00d72.png)

I first thought that maybe it's the pink line since the GPUs sit at 0% utilization, but even when I maxxed all of them to 100% the line didn't move. Any idea what could be causing this?

**UPDATE**
Mystery solved - there are so many GPUs that the charts got squished into what looks like a line. When I vertically expanded the window, the charts appeared as expected. I don't know how difficult this would be in QT, but would it be possible to make the window scrollable? Right now I cannot access the bottom values since I have to make the window taller than my screen to see the charts at all, but that pushes the stats outside the screen area.
![image](https://user-images.githubusercontent.com/2159464/217878154-16e11811-06fb-483b-9184-a841a400660b.png)

**Comment by congard** [comment]
Hi, could you test the latest `master`, please? Manual building is described [here](https://github.com/congard/nvidia-system-monitor-qt#dependencies) and [here](https://github.com/congard/nvidia-system-monitor-qt#other)

**Comment by jankais3r** [comment]
Hi,

Many thanks for working on my request so promptly. I compiled the latest version, but there are still some things to resolve.

![image](https://user-images.githubusercontent.com/2159464/218282529-1276e9ad-e1d7-4ff6-9c40-af44d5fd3240.png)

- [x] Allow vertical resizing of the window
- [ ] When a window is made smaller than is the height of the content, scrollbars should appear so the cut off content can be scrolled to
- [ ] The charts should not shrink into a single pixel line

**Comment by congard** [comment]
So, I've set min height of charts to 96 and enabled scrolling:
![image](https://user-images.githubusercontent.com/35779485/218337615-2bca1c26-67d1-4927-a0cb-793459e4fdab.png)

Also, I've decreased vertical spacing for the legend layout.

Could you test the latest `master`, please?

**Comment by jankais3r** [comment]
Hi, this is a big improvement, but it still doesn't work 100%.

1) The scrollbar only shows up when the window can't fit the charts + 1 row of GPUs. It should appear much sooner, as soon as the first GPU row disappears.

https://user-images.githubusercontent.com/2159464/218342570-f437fb8e-87ae-492c-81d9-cc810afb0971.mov

2) The GPUs are not aligned
![image](https://user-images.githubusercontent.com/2159464/218342610-652a103c-d7cc-4695-a221-21761e16a7e8.png)

Thanks a lot for your continued work on this.

**Comment by congard** [comment]
Well, I guess it should be ok now. Could you test the latest `master`, please?

**Comment by jankais3r** [comment]
Perfect now.

![image](https://user-images.githubusercontent.com/2159464/218550467-cf796494-08d5-4efa-84b7-7244ac9b6a06.png)

Thank you very much!
