### ISSUE TITLE
memory usage isn't as expected

### ISSUE THREAD

**Issue by candytaco** [congard/nvidia-system-monitor-qt#3]
The memory usage tab displays `nvidia-smi`'s `utilization.memory` value, which is "
Percent of time over the past sample period during which global (device) memory was being read or written" (from the [useful queries page](https://nvidia.custhelp.com/app/answers/detail/a_id/3751/~/useful-nvidia-smi-queries)) and not the amount of vRAM in use.

I changed https://github.com/congard/nvidia-system-monitor-qt/blob/599b650db79f121024b2441239fe04418e50d055/src/utilization.cpp#L188-L191

to
```
        memoryData[i - 1].total = std::atoi(split(data[1], " ")[0].c_str());
        memoryData[i - 1].free = std::atoi(split(data[2], " ")[0].c_str());
        memoryData[i - 1].used = std::atoi(split(data[3], " ")[0].c_str());
        udata[i - 1].level = memoryData[i - 1].used * 100 / memoryData[i - 1].total;
```
in my local build to make the tab display percent of vRAM in use

**Comment by congard** [comment]
Thanks for the report! I apologize for such a late reply, I will fix it as soon as possible
