### ISSUE TITLE
GPU memory use values different to ones in nvidia-smi

### ISSUE THREAD

**Issue by ZeevoX** [congard/nvidia-system-monitor-qt#4]
I opened `nvidia-system-monitor-qt` and `nvidia-smi` side-by-side to compare values, and for some reason the GPU memory use values per process are significantly smaller in this application than in the `nvidia-smi` cli interface. I have attached a screenshot below.

Which one should I trust? Is this something to do with the way this application retrieves the values from `nvidia-smi`?

![nvidia-smi vs nvidia-system-monitor-qt](https://user-images.githubusercontent.com/8385172/71980063-1ec3b380-3217-11ea-8c66-0113925f376e.png)

ZeevoX

**Comment by hrdkjain** [comment]
`nvidia-system-monitor-qt` shows GPU Memory Use in % instead of MB.

**Comment by congard** [comment]
Fixed with #9
