### ISSUE TITLE
doesn't work for Acer Aspire E1 571G (Geforce 710m + i3 3110m in nvidia-optimus) at all

### ISSUE THREAD

**Issue by Artemka091102** [congard/nvidia-system-monitor-qt#7]
![2020-05-13-203559_1366x768_scrot](https://user-images.githubusercontent.com/40118355/81845608-7a050a00-9559-11ea-8055-53fafcaa82e4.png)

**Comment by congard** [comment]
Hi, please, share the output of the following commands:
1. `nvidia-smi --query-gpu=count --format=csv`
2. `nvidia-smi pmon -c 1`
3. `nvidia-smi --query-gpu=utilization.gpu --format=csv`
4. `nvidia-smi --query-gpu=utilization.memory,memory.total,memory.free,memory.used --format=csv`

**Comment by congard** [comment]
Closed, because:
1. Your GPU doesn't support a lot of monitoring features (it seems that only temperature and memory usage supporting)
2. There was a huge refactoring and pull requests were merged since your issue
